BEGIN;

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL DEFAULT 'user';
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "banned" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "banReason" TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "banExpires" TIMESTAMPTZ;
ALTER TABLE "session" ADD COLUMN IF NOT EXISTS "impersonatedBy" TEXT;

CREATE INDEX IF NOT EXISTS "idx_user_banned" ON "user" ("banned") WHERE "banned" = TRUE;

COMMIT;
